### ISSUE TITLE
windows 上 preview 失败

### ISSUE THREAD

**Issue by phobal** [ineo6/mini-deploy#3]
#### 环境
* 操作系统：Windows server 2008 / windows 7 旗舰版
* 微信小程序开发者工具：v1.02.200420
* mini-deploy@v1.4.5
#### 操作步骤
1、在项目中安装 mini-deploy 依赖
2、在 scripts 中添加执行命令：
``` js
"preview": "mini-deploy"
```
3、执行命令：  
``` bash
yarn preview
```
报如下错误，一直处于 prepare preview  的状态

#### 报错信息

![image](https://user-images.githubusercontent.com/9244211/79930644-a27a7680-847b-11ea-8289-bf9e6de80d14.png)

#### 期望结果

在 mac 上操作步骤同上，能在项目的根目录下生成小程序预览二维码 preview.png 图片

盼回复，谢谢！

**Comment by ineo6** [comment]
收到，`v1.02.200420`版本对`api`进行了调整，所以需要测试，以及兼容新旧版本，会尽快发布新版本。

**Comment by ineo6** [comment]
请尝试`v2.0.0`版本
