### ISSUE TITLE
小程序已经提供ci工具

### ISSUE THREAD

**Issue by chikinlee** [ineo6/mini-deploy#4]
小程序已经提供ci工具，参考教程文章： https://www.jianshu.com/p/df1b55b1680e
官方文档地址： https://developers.weixin.qq.com/miniprogram/dev/devtools/ci.html

**Comment by ineo6** [comment]
封装新的工具 [mp-ci](https://github.com/ineo6/mp-ci)（基于官方`ci`），自动提取`appid`，内置提交信息生成，并美化信息展示，欢迎使用。
